"""Shared visualization theme: colors, palettes, style constants."""

BG_COLOR = "#0a0a1a"
TEXT_COLOR = "#ccddee"
GRID_COLOR = "#1a2a3a"
LONE_PAIR_COLOR = "#ffaa33"
BOND_COLOR = "#aabbcc"
ANGLE_ARC_COLOR = "#44ccff"
POSITIVE_COLOR = "#3399ff"
NEGATIVE_COLOR = "#ff5533"
NEUTRAL_COLOR = "#44ccff"
ENERGY_COLOR = "#ffaa33"
